services:

  # MongoDB for product service
  mongo_products:
    container_name: mongo_products
    image: mongo:8.0.5
    ports:
      - "27017:27017"
    # volumes:
    #   - mongo-products-data:/data/db

  # MongoDB for user service
  mongo_users:
    container_name: mongo_users
    image: mongo:8.0.5
    ports:
      - "27018:27017"
    # volumes:
    #   - mongo-users-data:/data/db

  # Postgres for order service
  postgres_orders:
    image: postgres:17.0
    ports:
      - "5431:5432"
#    volumes:
#      - postgres-orders-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=order-service
      - POSTGRES_USER=order-service
      - POSTGRES_DB=OrdersDB

  # Postgres for inventory service
  postgres_inventories:
    image: postgres:17.0
    ports:
      - "5432:5432"
#    volumes:
#      - postgres-inventories-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=inventory-service
      - POSTGRES_USER=inventory-service
      - POSTGRES_DB=InventoryDB

      
  zookeeper:
    image: bitnami/zookeeper:3.9.3
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    # volumes:
    #   - kafka_zookeeper:/opt/zookeeper-3.6.1/data
    
  kafka:
    image: bitnami/kafka:3.9.0
    container_name: kafka
    ports:
      - "9093:9093"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://0.0.0.0:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
    # volumes:
    #   - kafka_kafka:/opt/kafka_2.12-2.2.0/logs
    depends_on:
      - zookeeper
  
  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.2
    container_name: kafka-ui
    restart: unless-stopped
    ports:
      - "8090:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    depends_on:
      - kafka
